Repository namdng09/flower-ecommerce, pull requests merged in 2025-07, with the labels that each got.

#37 Feat/namdng09/manage order module
  server/src/modules/address/addressController.ts
  server/src/modules/address/addressModel.ts
  server/src/modules/order/orderController.ts
  server/src/modules/order/orderModel.ts
  server/src/modules/product/productController.ts
Labels: feature

#39 Feat/namdng09/manage order module
  server/src/modules/order/orderController.ts
  server/src/modules/order/orderModel.ts
Labels: bug

#40 Feat/anhduc/change folder structure
  server/src/modules/address/addressController.ts
  server/src/modules/address/addressRoute.ts
  server/src/modules/address/addressService.ts
  server/src/modules/auth/authController.ts
  server/src/modules/auth/authRoute.ts
  server/src/modules/auth/authService.ts
  server/src/modules/cart/cartController.ts
  server/src/modules/cart/cartService.ts
  server/src/modules/category/categoryController.ts
  server/src/modules/category/categoryRoute.ts
  server/src/modules/category/categoryService.ts
  server/src/modules/favourite/favouriteController.ts
  server/src/modules/favourite/favouriteService.ts
  server/src/modules/order/orderController.ts
  server/src/modules/order/orderModel.ts
  server/src/modules/order/orderService.ts
  server/src/modules/product/productController.ts
  server/src/modules/product/productService.ts
  server/src/modules/user/userController.ts
  server/src/modules/user/userRoute.ts
  server/src/modules/user/userService.ts
  server/src/modules/variant/variantController.ts
  server/src/modules/variant/variantRoute.ts
  server/src/modules/variant/variantService.ts
Labels: enhancement

#51 Fix/trangvu/create order ver3
  client/src/app/home/order/page.tsx
  client/src/components/FeaturedProductsC/FeaturedProductsC.tsx
  client/src/components/cart/CartItemsList.tsx
  client/src/components/order/OrderPage.tsx
  client/src/components/order/OrderSuccess.tsx
  client/src/components/productList/ProductList.tsx
  client/src/routers/router.tsx
Labels: enhancement

#54 Feat/namdng09/manage order module
  server/src/modules/address/addressController.ts
  server/src/modules/address/addressRoute.ts
  server/src/modules/address/addressService.ts
  server/src/modules/auth/authService.ts
  server/src/modules/order/orderController.ts
  server/src/modules/order/orderModel.ts
  server/src/modules/order/orderService.ts
  server/src/modules/product/productController.ts
  server/src/modules/product/productService.ts
  server/src/modules/variant/variantService.ts
Labels: bug

#55 Feat/namdng09/manage order module
  server/src/modules/address/addressController.ts
  server/src/modules/address/addressRoute.ts
  server/src/modules/address/addressService.ts
  server/src/modules/order/orderService.ts
Labels: bug
